# See docs/examples
# http://doc.gitlab.com/ce/ci/quick_start/README.html
# http://doc.gitlab.com/ce/ci/yaml/README.html

# GitLab CI template for Go tests. Note this installs
# a new working copy of Go in a non-standard path such
# that sudo/root is not needed for the install stage.

# note that this particular install-environment stage
# is overly verbose in order to debug anything tricky
# or weird in your environment - feel free to trim it 
# down as needed

stages:
 # - install-environment
  - build
  - baseline


build-maya:
   stage: build
   script: 
    - echo "success"

baseline-image:
  stage: baseline
  image: atulabhi/kops:v8
  script:
    - "curl -X POST -F token=a70ff62f6fb0f8013c687087ae5565 -F ref=test https://gitlab.com/api/v4/projects/7642571/trigger/pipeline"
#build-maya:
#  stage: build
#  script:
#    - cd $CURRENT_BUILD_PATH
#    - go build

#test-my-project:
#  stage: test
#  script:
#    - cd $CURRENT_BUILD_PATH
#    - go test

